# Generated by Django 5.2.8 on 2025-12-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_category_unique_together_alter_category_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'type')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
